images:
  - name: markpollack/spring-sample-app  # used for Kustomize matching
    newName: harbor.marygabry.name/spring-sample-app/spring-sample-app-tbs # CHANGE
    digest: sha256:3ee4422b552a13f140f6bc77cd84fb400a12685c6bbb210d5bb7b5c564477233
configMapGenerator:
  - name: spring-configmap-env  # naming convention for reference
    envs:
      - env.properties
resources:
  - ../../base
